### ISSUE TITLE
pow with floats fails in cuda

### ISSUE THREAD

**Issue by hschwane** [kthohr/gcem#11]
using 
`constexpr float result = gcem::pow(5,0.5); `
fails with the following error:
```
error: function call must have a constant value in a constant expression
.../external/gcem/gcem_incl/log.hpp(106): note: floating-point values cannot be compared
.../external/gcem/gcem_incl/log.hpp(144): note: called from:
.../external/gcem/gcem_incl/pow.hpp(37): note: called from:
.../external/gcem/gcem_incl/pow.hpp(50): note: called from:
.../external/gcem/gcem_incl/pow.hpp(79): note: called from:
```

I'm using the nvidia nvcc compiler version 9.1 with gcc 6.5.
Using pow with integers works fine.

**Comment by kthohr** [comment]
The library is tested against GCC versions 5, 6, 7 and 8. This sounds like an NVCC problem.

**Comment by hschwane** [comment]
Most likely yes, since it works in a non cuda project. Any ideas for a workaround? I tried to look into your code already but I'm not sure what's going on.

**Comment by kthohr** [comment]
I’ll push a potential fix later today.

**Comment by kthohr** [comment]
Can you check again using the latest version?

**Comment by hschwane** [comment]
Commit 95700ac seems to have fixed it. Everything is compiling and giving the expected results. Thanks so much for the quick help!
