### ISSUE TITLE
Support for nearest integer floating point operations

### ISSUE THREAD

**Issue by dodomorandi** [kthohr/gcem#13]
The following functions are not available:
* ceil
* trunc
* nearbyint
* *round
* *rint

Is there a plan to implement them in the future?

**Comment by kthohr** [comment]
I've added (or exposed) functions for `ceil`, `floor`, `round` and `trunc`. But I likely won't add functionality that calls the current rounding mode.

**Comment by dodomorandi** [comment]
Thank you so much for your efforts! You are right that it is pretty meaningless to use rounding modes in constexpr context. Thank you again!
