### ISSUE TITLE
round(), floor() and ceil() for big numbers

### ISSUE THREAD

**Issue by jan-moeller** [kthohr/gcem#16]
The following code doesn't compile:

```c++
constexpr long double const a = 42e32;
constexpr auto const f = gcem::round(a);
```
My g++-7.4.0 gives me:

```
file.cpp: In function ‘int main()’:
file.cpp:49:38:   in constexpr expansion of ‘gcem::round<long double>(4.20000000000000011729e+33l)’
./../include/gcem_incl/round.hpp:70:33:   in constexpr expansion of ‘gcem::internal::round_check<long double>(((long double)x))’
./../include/gcem_incl/round.hpp:52:35:   in constexpr expansion of ‘gcem::internal::round_int<long double>(gcem::abs<long double>(((long double)x)))’
./../include/gcem_incl/round.hpp:33:37:   in constexpr expansion of ‘gcem::internal::find_whole<long double>(((long double)x))’
./../include/gcem_incl/find_whole.hpp:37:42:   in constexpr expansion of ‘gcem::internal::floor_check<long double>(((long double)x))’
file.cpp:49:40: error: overflow in constant expression [-fpermissive]
  constexpr auto const f = gcem::round(a);
                                        ^
file.cpp:49:40: error: overflow in constant expression [-fpermissive]
file.cpp:49:40: error: overflow in constant expression [-fpermissive]
```

The same is true if you replace `round` with `floor` or `ceil`.

I think it should at least be documented that these functions will fail if the input is outside of the bounds of a `long long int`. Alternatively, maybe it is possible to fall back to a different algorithm for large numbers or deduce that all numbers larger than `std::numeric_limits<long long int>::max()` are integers anyway (this might at least be true for the smaller floating point types like `float`, I didn't check). In the latter case, it would be fine to just return the input unmodified.

**Comment by Hector-The-Coder** [comment]
The way floating points are designed is that, the bigger the number is, the more precision you lose, and doing some testing i found the threshold values for each type, which interesting is that they are still convertible to integers, I'll fork this and implement the support and make a PR
