### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by remarkable-tools** [kthohr/gcem#21]
there's might** be overflow issues 

e.g. 
abs function returns x == T(0) ?  T(0) :  x < T(0) ? - x : x

since abs(min limit) == max_limit + 1
the result for abs(INT64_MIN) is -9223372036854775808 (negative)
INT64_MIN == 0 ? 0 : INT64_MIN < 0 ? -INT64_MIN : INT64_MIN

** = i didn't executed the code since i'm using it as reference

**Comment by kthohr** [comment]
The result of `gcem::abs(INT64_MIN)` matches the result of`std::abs(INT64_MIN)`.
