### ISSUE TITLE
conda-forge feedstock

### ISSUE THREAD

**Issue by tdegeus** [kthohr/gcem#23]
Hi @kthohr 

Thanks for this package!!

I would like to rely on your wonderful package. Therefore I would also need a conda-forge feedstock. Would you be interested to become a co-maintainer ? 

If so please comment "I agree to be a maintainer" in the PR : https://github.com/conda-forge/staged-recipes/pull/14818 . 
(If you see this after the PR is merged I will add you to the feedstock!)

**Comment by kthohr** [comment]
Thanks for doing that; I've updated the ReadMe file to point to conda-forge. 

Happy to be added as a maintainer, whenever you might see this.
