### ISSUE TITLE
Incompatibility with math.h

### ISSUE THREAD

**Issue by NielsPT** [kthohr/gcem#29]
Hi, this is a small thing. 
I've inherited inclusion of some macros from <math.h> from some other libraries that I use in a project. The compiler tries to expand in your awesome gcem library, braking the code. An easy fix is to add 

```c++
#undef abs
#undef round
#undef signbit
```

just before inclusion of <gcem>. Looking into <cmath>, they've done something similar (at least for ARM GCC):

```c++
// Get rid of those macros defined in <math.h> in lieu of real functions.
#undef abs
#undef div
#undef acos
#undef asin
#undef atan
#undef atan2
#undef ceil
#undef cos
#undef cosh
#undef exp
#undef fabs
#undef floor
#undef fmod
#undef frexp
#undef ldexp
#undef log
#undef log10
#undef modf
#undef pow
#undef sin
#undef sinh
#undef sqrt
#undef tan
#undef tanh
```

Maybe this would be an idea for your lib? It'l take you all of 5 seconds to make the change and ensure compatibility with older code bases. Just a thought.

Thanks and have a nice day.

Niels

**Comment by kthohr** [comment]
Thanks for the note. I have added the suggested `undef`s.

```c++
#undef abs
#undef round
#undef signbit
```
