### ISSUE TITLE
pow(), log(), log2(), log10() broken for small input arguments

### ISSUE THREAD

**Issue by mhx** [kthohr/gcem#30]
First of all, thank you so much for this library! I've been using it to build a compile-time filter design library [1] and it's been working (almost) flawlessly! :)

When using the `pow()` function with a small base argument to compute n-th roots, I found that it would always return zero.

```
#include <cmath>
#include <iomanip>
#include <iostream>

#include <gcem.hpp>

int main()
{
    std::cout << std::setprecision(20);
    std::cout << "std::pow():  " << std::pow(1e-20, 1.0/8.0) << "\n";
    std::cout << "gcem::pow(): " << gcem::pow(1e-20, 1.0/8.0) << "\n";
}
```

This will output:

```
std::pow():  0.0031622776601683793944
gcem::pow(): 0
```

So I dug a little deeper and the reason is that `log()`, which is used to implement `pow()`, has this check:

```
            // x ~= 0
            GCLIM<T>::epsilon() > x ? \
                - GCLIM<T>::infinity() :
```

Now `::epsilon()` is typically *much* larger than the smallest representable floating point number and as a result, `log()` will always return infinity for small input arguments. The same check is present in `log2()` and `log10()`.

Replacing this check with a simple check for non-zeroness makes the code work as expected.

[1] Part of [libembedded](https://github.com/mhx/libembedded/tree/experimental-filters#an-experimental-compile-time-iir-filter-design-library).

**Comment by kthohr** [comment]
Great, thanks for catching this! 

On your solution: I'd prefer not to do exact comparisons for floating point types (e.g., `x == T(0)`), and so I've implemented something a little different (but kept your tests). This issue went beyond just the `log` functions, and so I have made similar changes throughout the library (replacing `epsilon()` with `min()`).

Please let me know if you catch anything else like this!

**Comment by mhx** [comment]
Thank you very much for looking into this so quickly!

I haven't actually had look at your change yet and I completely agree about exact comparisons on floating point types in general. But I think that in case of `log`, zero is the only case in which the function should yield infinity, so a comparison with zero seemed reasonable here. But if you've kept my tests, that means it's still going to pass for the `min` case. :)
