### ISSUE TITLE
Inverse square root

### ISSUE THREAD

**Issue by hgkjshegfskef** [kthohr/gcem#33]
An inverse square root is a rather popular function. Would be nice to have it. [Wikipedia](https://en.wikipedia.org/wiki/Fast_inverse_square_root) suggests a constexpr implementation. Further sections also reference research on better magic number, e.g. 10.1109/JPROC.2020.2991885.

**Comment by kthohr** [comment]
I've added a basic `inv_sqrt` function to the library, but it is not a `constexpr` version of the fast inverse square-root function. The suggestion in that article requires C++20 functionality.
