### ISSUE TITLE
sqrt fails for DBL_MAX

### ISSUE THREAD

**Issue by reder2000** [kthohr/gcem#35]
gcem::sqrt(DBL_MAX) fails  with msvc or clang for the following reason :

failure was caused by evaluation exceeding call depth limit of 512 (/constexpr:depth<NUMBER>)

not very important (I can replace the value) but you may have wanted to know

**Comment by kthohr** [comment]
Which version of clang are you using? And I'm assuming this is on a Windows machine? 

I just tried 

``cpp
gcem::sqrt(std::numeric_limits<double>::max())
``

And it works just fine (and is within `1.110e-16` of `std::sqrt`).

**Comment by reder2000** [comment]
apparently it's clang-cl v11.
I've tried gcc12 (wsl) and clang 14 (ubuntu 22) and msvc. 
All with clean github checkout.
All fail for more or less the same reason.

to be perfectly clear, this fails:

constexpr auto v = gcem::sqrt(std::numeric_limits<double>::max());

it's ok without constexpr

**Comment by kthohr** [comment]
Ah, my mistake. When compiling, you might want to set `-fconstexpr-depth` to something larger than the default value. Using clang 13, `-fconstexpr-depth=650` seems to work for me.

**Comment by reder2000** [comment]
Well that's an impressive number. Given the multiplicative nature of sqrt couldn't something be done between exponent and mantissa ? (I'm no expert, this may be a stupid idea).

**Comment by kthohr** [comment]
Not a stupid idea :) I use a similar approach for calculating `log`. I'll experiment with this for `sqrt` and see if that improves things.

**Comment by kthohr** [comment]
Just pushed a simple solution.
