### ISSUE TITLE
Check for C++ 11 compiler fails for x86_64-w64-mingw32-g++

### ISSUE THREAD

**Issue by n-burger** [kthohr/gcem#36]
The check for a C++ 11 compiler fails when using x86_64-w64-mingw32-g++:

```
-- GCE-Math version 1.16.0
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
CMake Error at build/_deps/gcem-src/CMakeLists.txt:50 (message):
  Unsupported compiler /usr/lib64/ccache/x86_64-w64-mingw32-g++ GCEM requires
  a C++11-compatible compiler.
```

**Comment by kthohr** [comment]
Update your compiler, I guess?

**Comment by n-burger** [comment]
I am using the latest version v11.2.1 (see my updated comment above), which supports C++ 11, so I don't think it is an issue of the compiler.

**Comment by kthohr** [comment]
Check if your compiler supports `-std=c++11`, as needed here:

https://github.com/kthohr/gcem/blob/master/CMakeLists.txt#L45

If not, replace with what you need. (This is a Windoze and CMake issue, not really a GCEM library issue.)
