### ISSUE TITLE
Performance optimisation proposal

### ISSUE THREAD

**Issue by EmergReanimator** [kthohr/gcem#42]
I made some preliminary performance benchmarks on Cortex-M3.

### sqrt
* 23% performance gain with -O1
* 21% performance gain with -Os

Besides the performance gain, the memory requirements are lower and most important **deterministic**.
This is especially crucial for embedded systems.

### That's why I propose to consider loop based calculations instead of recursion based.

----
_arm-none-eabi-gcc (Fedora 13.2.0-5.fc40) 13.2.0_

### -O1
-mcpu=cortex-m3 -mthumb -O1 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding 

### -Os
-mcpu=cortex-m3 -mthumb -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding 

----
`sqrt` implemented in loop

```
-O1

sqrt(0.6) =  0.77460: 12448
floor(0.6) =  0.00000: 1272
fabs(0.6) =  0.60000: 212
log(0.6) = -0.51083: 29780
```

```
-Os

sqrt(0.6) =  0.77460: 11825
floor(0.6) =  0.00000: 1262
fabs(0.6) =  0.60000: 241
log(0.6) = -0.51083: 29925
```

----
`sqrt` implemented recursively

```
-O1

sqrt(0.6) =  0.77460: 16359
floor(0.6) =  0.00000: 1265
fabs(0.6) =  0.60000: 207
log(0.6) = -0.51083: 30062
```

```
-Os

sqrt(0.6) =  0.77460: 15055
floor(0.6) =  0.00000: 1332
fabs(0.6) =  0.60000: 240
log(0.6) = -0.51083: 29429
```

**Comment by EmergReanimator** [comment]
Here is the approach I would suggest:
https://github.com/kthohr/gcem/compare/master...EmergReanimator:gcem:welcome_to_embedded_world

**Comment by kthohr** [comment]
It's not clear what your benchmarking exercise is actually measuring, or why you included functions like `floor`... Your proposal is also not compatible with C++11. Loops are already used in functions such as `exp` and `log` when C++14(+) is detected. I'll consider implementing something similar for `sqrt` in the future.

**Comment by EmergReanimator** [comment]
> It's not clear what your benchmarking exercise is actually measuring, or why you included functions like `floor`... Your proposal is also not compatible with C++11. Loops are already used in functions such as `exp` and `log` when C++14(+) is detected. I'll consider implementing something similar for `sqrt` in the future.

Thanks for your prompt reply!

Let me give you some background of my request.
There are limited mathematical functions available in `freestanding` environment. 
https://en.cppreference.com/w/cpp/freestanding

`clang` and GCC 13+ does not provide me the functions mentioned above (`sqrt`, `floor`, `fabs`, `log`) any more.

That's why I need to implement those in scope of my application source code base.

----

> It's not clear what your benchmarking exercise is actually measuring,

The raw CPU cycles are measured like follows:

    {
        clock_t start = clock();
        float r = math::sqrt(0.6f);
        clock_t diff = clock() - start;
        printf("sqrt(0.6) = %8.5f: %lu\n", r, diff);
    }

    {
        clock_t start = clock();
        float r = math::floor(0.6f);
        clock_t diff = clock() - start;
        printf("floor(0.6) = %8.5f: %lu\n", r, diff);
    }

    {
        clock_t start = clock();
        float r = math::fabs(0.6f);
        clock_t diff = clock() - start;
        printf("fabs(0.6) = %8.5f: %lu\n", r, diff);
    }

    {
        clock_t start = clock();
        float r = math::log(0.6f);
        clock_t diff = clock() - start;
        printf("log(0.6) = %8.5f: %lu\n", r, diff);
    }

**Comment by EmergReanimator** [comment]
> Your proposal is also not compatible with C++11.

The g++ tricked me. I modified the code to be compatible with C+11 standard.
https://github.com/kthohr/gcem/compare/master...EmergReanimator:gcem:welcome_to_embedded_world
